// 此lib中的方法根据情况提取公用，以及根据不同页面设置适用于不同页面的方法，先放在一起做练习
export class Lib {
    constructor(config = {}) {
        this.property = {
            width: 1920,
            height: 1080,
            fps: 25,
            color: "#FFFFFF"
        }
        this.images = {}
        if(Object.prototype.toString.call(config) === '[object Object]') {
            this.property = Object.assign({}, this.property, config)
        }
    }
    setImg(item, id) {
        this.images[id] = new window.createjs.Bitmap(item)
        this.images[id].nominalBounds = new window.createjs.Rectangle(0,0,670,539)
    }
    setUnit(config) {
        if(Object.prototype.toString.call(config) !== '[object Object]') {
            return
        }
        // if(stage.__proto__ !== window.createjs.Stage.prototype) {
        //     return
        // }
        this.mc = new window.createjs.MovieClip(config)
        this.mc.nominalBounds = new window.createjs.Rectangle(0,0,1356.3,58)
        // stage.addChild(this.mc)
        const shape = new window.createjs.Shape()
        shape.graphics.f("#EBECDC").s().p("EhoYAEhQhkAAAAhkIAAl5QAAhkBkAAMDQxAAAQBkAAAABkIAAF5QAABkhkAAg")
        shape.setTransform(678.2,29)
        this.mc.timeline.addTween(window.createjs.Tween.get(shape).wait(45))
        // this.mc.gotoAndPlay("start")
    }
    setText(config) {
        if(Object.prototype.toString.call(config) !== '[object Object]') {
            return
        }

        // if(stage.__proto__ !== window.createjs.Stage.prototype) {
        //     return
        // }
        this.text = new window.createjs.MovieClip(config)
        this.text.nominalBounds = new window.createjs.Rectangle(0,0,443.2,48.7)
        // stage.addChild(this.text)

        // 文字打散
        const shape_0 = new window.createjs.Shape()
        shape_0.graphics.f("#FFFFFF").s().p("AOPB2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgAOtgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAHRB2QgagdAAg0QAAg4AggcQAagWAnAAQArAAAbAbQAbAcAAAwQAAAogMAXQgMAXgXANQgXAMgbAAQgsAAgbgbgAHsgVQgRAUAAAmQAAAnARAVQARATAbABQAagBARgTQASgVAAgoQAAglgSgUQgRgTgagBQgbAAgRAUgAABB2QgZgdAAgzQAAgyAZgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgAAfgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAjKBzIAAAZIghAAIAAkcIAkAAIAABmQAWgbAiAAQAUAAARAHQARAIALAOQALAOAGAUQAGARAAAXQAAA1gaAdQgaAdglAAQglAAgVgegAi6gVQgQAUAAAkQAAAmAKAQQAQAbAdABQAXgBARgTQAQgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgArxCKQgQgHgIgLQgIgKgDgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOALAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADNIgfAAIAAgeQgZAjgpAAQgTAAgPgHgAMnCMIAAh+QAAgTgEgKQgEgMgLgGQgKgGgOAAQgXAAgQAOQgQAOAAAmIAABxIgjAAIAAjNIAfAAIAAAeQAXgjArABQATAAAQAGQAPAHAIALQAIALADAPQACAKAAAWIAAB/gADPCMIAAjNIAgAAIAAAgQAMgXAKgGQAKgIANABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgEAMQgGARAAAWIAABsgAlBCMIAAiCQAAgUgEgIQgDgKgJgFQgJgGgMAAQgWAAgPAPQgOAOAAAeIAAB4IgjAAIAAiHQAAgVgJgLQgIgMgUAAQgPAAgMAHQgNAJgGAPQgFANAAAcIAABrIgjAAIAAjNIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAOAKAHARQAYglAoABQAeAAARARQARAQAAAkIAACMgAt4CMIiWjfIAADfIgkAAIAAkcIAnAAICWDfIAAjfIAkAAIAAEcg")
        shape_0.setTransform(222.3,24.1)
    
        const shape_1 = new window.createjs.Shape()
        shape_1.graphics.f("#FFFFFF").s().p("AN2B2QgagdAAg0QAAg4AggcQAbgWAmAAQArAAAbAbQAbAcAAAwQAAAogMAXQgMAXgXANQgXAMgbAAQgsAAgbgbgAORgVQgRAUAAAmQAAAnARAVQARATAbABQAagBASgTQARgVAAgoQAAglgRgUQgSgTgagBQgbAAgRAUgAAWB2QgZgdAAgzQAAgyAZgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggWARQgYASgkAAQguAAgagbgAA0gYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgagBQgZABgQAQgAi1BzIAAAZIggAAIAAkcIAjAAIAABmQAWgbAjAAQATAAARAHQARAIALAOQALAOAGAUQAGARABAXQAAA1gbAdQgaAdglAAQglAAgVgegAilgVQgQAUAAAkQAAAmAKAQQARAbAcABQAXgBARgTQARgVAAgnQAAgngQgUQgRgSgWgBQgYABgRATgArcCKQgQgHgIgLQgIgKgDgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOAMAIQAKAIAQAAQAQAAAOgIQAOgIAFgOQAGgOAAgbIAAhtIAkAAIAADNIggAAIAAgeQgZAjgpAAQgSAAgQgHgAHyCJQgKgGgFgKQgDgJAAggIAAh2IgbAAIAAgbIAbAAIAAgzIAjgWIAABJIAjAAIAAAbIgjAAIAAB4QgBAPACAEQACAEAFADQAEADAHgBIAQgBIAEAfQgOADgMAAQgTAAgLgGgALmCMIgpidIgqCdIglAAIg/jNIAkAAIAuCjIAKgrIAhh4IAkAAIApCeIAwieIAiAAIhBDNgADkCMIAAjNIAgAAIAAAgQAMgXAKgGQALgIAMABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgDAMQgHARABAWIAABsgAksCMIAAiCQAAgUgDgIQgEgKgJgFQgJgGgMAAQgWAAgOAPQgPAOAAAeIAAB4IgjAAIAAiHQAAgVgJgLQgIgMgUAAQgOAAgNAHQgMAJgHAPQgFANAAAcIAABrIgjAAIAAjNIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAPAKAGARQAYglAoABQAfAAAQARQARAQAAAkIAACMgAtjCMIiWjfIAADfIgkAAIAAkcIAnAAICWDfIAAjfIAkAAIAAEcg")
        shape_1.setTransform(222.4,24.1)
    
        const shape_2 = new window.createjs.Shape()
        shape_2.graphics.f("#FFFFFF").s().p("AQJB2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgAQngYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAMrB2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgANJgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAh3B2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAZAbQAaAdAAAyIAAAJIiZAAQACAiASASQARATAaAAQATAAAOgLQAOgKAGgXIAkAFQgJAggXARQgVASgkAAQguAAgagbgAhZgYQgRAPgCAaIByAAQgCgZgJgNQgRgTgbgBQgYABgQAQgAlEBzIAAAZIghAAIAAkcIAkAAIAABmQAWgbAiAAQAUAAARAHQARAIALAOQALAOAGAUQAGARAAAXQAAA1gaAdQgaAdglAAQglAAgVgegAk0gVQgQAUAAAkQAAAmAKAQQAQAbAdABQAXgBARgTQAQgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgAtrCKQgQgHgIgLQgIgKgDgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOALAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADNIgfAAIAAgeQgZAjgpAAQgTAAgPgHgAFjCJQgKgGgFgKQgEgJAAggIAAh2IgaAAIAAgbIAaAAIAAgzIAjgWIAABJIAjAAIAAAbIgjAAIAAB4QAAAPACAEQACAEAEADQAEADAIgBIAPgBIAFAfQgOADgMAAQgTAAgLgGgAKWCMIAAjNIAgAAIAAAgQAMgXAKgGQAKgIANABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgEAMQgGARAAAWIAABsgAI+CMIAAiDQAAgZgLgLQgLgNgVAAQgQAAgOAJQgOAIgFAOQgGAMAAAYIAABxIgjAAIAAkcIAjAAIAABnQAYgdAmABQAXgBARAKQARAIAHARQAIAQAAAcIAACDgABVCMIAAjNIAgAAIAAAgQAMgXAKgGQAKgIANABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgEAMQgGARAAAWIAABsgAm7CMIAAiCQAAgUgEgIQgDgKgJgFQgJgGgMAAQgWAAgPAPQgOAOAAAeIAAB4IgjAAIAAiHQAAgVgJgLQgIgMgUAAQgPAAgMAHQgNAJgGAPQgFANAAAcIAABrIgjAAIAAjNIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAOAKAHARQAYglAoABQAeAAARARQARAQAAAkIAACMgAvyCMIiWjfIAADfIgkAAIAAkcIAnAAICWDfIAAjfIAkAAIAAEcg")
        shape_2.setTransform(222.3,24.1)
    
        const shape_3 = new window.createjs.Shape()
        shape_3.graphics.f("#FFFFFF").s().p("AMfCMQgQgHgIgKQgIgLgDgPQgCgLAAgWIAAh/IAjAAIAABxQAAAcADAJQACAOALAIQALAIAQAAQAQAAANgIQAOgIAHgOQAFgOAAgbIAAhtIAjAAIAADOIgfAAIAAgfQgZAjgpAAQgTAAgPgHgAIqB4QgagcAAg1QAAg4AggbQAagXAnAAQArAAAbAcQAbAcAAAvQAAAogMAXQgMAXgXANQgXAMgbAAQgsAAgbgbgAJFgTQgRATAAAnQAAAoARAUQASAUAaAAQAaAAARgUQASgUAAgpQAAgmgSgSQgRgUgaAAQgaAAgSATgAgTB4QgbgdAAgyQAAgzAbgcQAZgdArAAQApAAAbAcQAbAcAAAyIgBAJIiZAAQADAiAPASQARATAaAAQATAAAOgLQAOgKAIgWIAkAEQgJAggXASQgXARgkAAQgtAAgZgbgAAJgWQgPAQgBAZIByAAQgDgYgLgNQgRgUgbAAQgYAAgQAQgAjfB1IAAAaIghAAIAAkdIAjAAIAABnQAWgcAiAAQAUAAARAHQARAIALAOQALAOAGAUQAHARAAAXQAAA1gbAdQgaAdglAAQglAAgUgegAjQgSQgQASAAAlQAAAmAKAQQAQAcAdAAQAXAAARgUQARgVgBgnQAAgngQgTQgPgTgXAAQgXAAgSAUgAsHCMQgQgHgIgKQgHgLgEgPQgCgLAAgWIAAh/IAjAAIAABxQAAAcACAJQAEAOAKAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADOIgfAAIAAgfQgZAjgpAAQgTAAgPgHgAPYCPIAAjOIAgAAIAAAgQAMgWAKgHQALgHAMAAQASAAASALIgMAhQgNgIgNAAQgLAAgKAHQgJAHgDAMQgHARABAWIAABtgAG2CPIAAiyIgfAAIAAgcIAfAAIAAgWQAAgVAEgKQAFgNANgJQAMgIAYAAQAPAAARADIgFAfQgKgCgKAAQgRAAgGAHQgHAGAAATIAAATIApAAIAAAcIgpAAIAACygAC5CPIAAjOIAgAAIAAAgQAMgWAKgHQAKgHANAAQASAAASALIgMAhQgNgIgMAAQgMAAgKAHQgIAHgEAMQgHARAAAWIAABtgAlXCPIAAiDQAAgTgDgJQgEgKgJgFQgJgGgMAAQgWAAgPAPQgNAOAAAeIAAB5IgkAAIAAiHQAAgVgIgMQgJgMgTAAQgPAAgNAIQgNAIgFAPQgGANAAAcIAABsIgjAAIAAjOIAgAAIAAAdQAJgPAQgJQARgJAUAAQAYAAAOAJQAOAKAHARQAYgkAoAAQAeAAARARQARARAAAhIAACPgAuOCPIiVjfIAADfIglAAIAAkdIAnAAICWDfIAAjfIAlAAIAAEdg")
        shape_3.setTransform(223.4,23.9)
    
        const shape_4 = new window.createjs.Shape()
        shape_4.graphics.f("#FFFFFF").s().p("AN5B4QgbgdAAgyQAAgzAbgcQAbgdArAAQApAAAbAcQAaAcAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgWIAkAEQgJAggXASQgXARgkAAQguAAgagbgAOXgWQgRAQgCAZIB0AAQgCgYgLgNQgRgUgbAAQgYAAgQAQgAAXB4QgZgdAAgyQAAgzAZgcQAbgdArAAQApAAAbAcQAaAcAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgWIAkAEQgJAggXASQgXARgkAAQguAAgagbgAA1gWQgRAQgCAZIB0AAQgCgYgLgNQgRgUgbAAQgYAAgQAQgAi0B1IAAAaIghAAIAAkdIAkAAIAABnQAWgcAiAAQAUAAARAHQARAIALAOQALAOAGAUQAGARAAAXQAAA1gaAdQgaAdglAAQglAAgVgegAikgSQgQASAAAlQAAAmAKAQQAQAcAdAAQAXAAARgUQAQgVAAgnQAAgngQgTQgQgTgXAAQgXAAgRAUgArbCMQgQgHgIgKQgIgLgDgPQgCgLAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOALAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADOIgfAAIAAgfQgZAjgpAAQgTAAgPgHgALbCPIhPjOIAlAAIAtB7QAHAUAGAVQAFgQAIgXIAuh9IAlAAIhPDOgAJJCPIAAjOIAjAAIAADOgAHiCPIAAiyIgfAAIAAgcIAfAAIAAgWQAAgVAEgKQAFgNANgJQAMgIAXAAQAPAAASADIgFAfQgLgCgKAAQgQAAgGAHQgHAGAAATIAAATIAoAAIAAAcIgoAAIAACygADlCPIAAjOIAgAAIAAAgQAMgWAKgHQAKgHANAAQASAAASALIgMAhQgNgIgNAAQgLAAgKAHQgJAHgEAMQgGARAAAWIAABtgAkrCPIAAiDQAAgTgEgJQgDgKgJgFQgJgGgMAAQgWAAgPAPQgOAOAAAeIAAB5IgjAAIAAiHQAAgVgJgMQgIgMgUAAQgPAAgMAIQgNAIgGAPQgFANAAAcIAABsIgjAAIAAjOIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAOAKAHARQAYgkAoAAQAeAAARARQARARAAAhIAACPgAtiCPIiWjfIAADfIgkAAIAAkdIAnAAICWDfIAAjfIAkAAIAAEdgAJJhlIAAgpIAjAAIAAApg")
        shape_4.setTransform(222.3,23.9)
    
        const shape_5 = new window.createjs.Shape()
        shape_5.graphics.f("#FFFFFF").s().p("AIjCAQgWgQgFghIAigGQADAVAOALQANAMAYAAQAYgBAMgJQAMgLAAgNQAAgLgLgHQgHgFgdgHQgmgKgPgHQgPgHgIgNQgIgNAAgNQAAgNAHgMQAGgMALgIQAIgGAPgFQAOgDAQAAQAYgBATAIQASAGAJANQAJAMADATIgiAGQgDgQgLgKQgLgJgVAAQgYAAgKAIQgLAJAAAKQAAAHAFAFQAEAEAJADIAfAJQAmAKAOAHQAPAGAIAMQAJAMAAATQAAARgKAQQgLAPgTAJQgTAIgZAAQgoAAgVgRgABTB2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgABxgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAh4BzIAAAZIghAAIAAkcIAkAAIAABmQAWgbAiAAQAUAAARAHQARAIAJAOQALAOAGAUQAGARAAAXQAAA1gZAdQgZAdglAAQglAAgVgegAhogVQgQAUAAAkQAAAmAKAQQAQAbAdABQAXgBARgTQAQgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgAqfCKQgQgHgIgLQgIgKgDgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOALAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADNIgfAAIAAgeQgZAjgpAAQgTAAgPgHgAO2CMIg2hSIg2BSIgrAAIBMhsIhGhhIAsAAIAgAxIAOAVIAQgVIAjgxIAqAAIhIBfIBNBugALeCMIAAjNIAjAAIAADNgAEhCMIAAjNIAgAAIAAAgQAMgXAKgGQAKgIANABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgEAMQgGARAAAWIAABsgAjvCMIAAiCQAAgUgEgIQgDgKgJgFQgJgGgMAAQgWAAgPAPQgOAOAAAeIAAB4IgjAAIAAiHQAAgVgJgLQgIgMgUAAQgPAAgMAHQgNAJgGAPQgFANAAAcIAABrIgjAAIAAjNIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAOAKAHARQAYglAoABQAeAAARARQARAQAAAkIAACMgAsmCMIiWjfIAADfIgkAAIAAkcIAnAAICWDfIAAjfIAkAAIAAEcgALehoIAAgoIAjAAIAAAog")
        shape_5.setTransform(222.9,24.1)
    
        const shape_6 = new window.createjs.Shape()
        shape_6.graphics.f("#FFFFFF").s().p("AN+B2QgbgdAAgzQAAgyAbgdQAbgcArAAQAqAAAaAbQAbAdAAAyIgBAJIiaAAQACAiARASQARATAaAAQAUAAANgLQAOgKAIgXIAkAFQgIAggXARQgYASgkAAQgtAAgbgbgAOcgYQgRAPgBAaIB0AAQgDgZgLgNQgRgTgagBQgZABgQAQgAHYB2QgbgdAAgzQAAgyAbgdQAbgcArAAQAqAAAaAbQAbAdAAAyIgBAJIiaAAQACAiARASQARATAaAAQAUAAANgLQAOgKAIgXIAkAFQgIAggXARQgYASgkAAQgtAAgbgbgAH2gYQgRAPgBAaIB0AAQgDgZgLgNQgRgTgagBQgZABgQAQgAEOCAQgVgQgGghIAjgGQADAVANALQAOAMAYAAQAYgBALgJQAMgLAAgNQAAgLgKgHQgHgFgdgHQgngKgPgHQgPgHgHgNQgIgNAAgNQAAgNAGgMQAHgMALgIQAIgGAOgFQAOgDAQAAQAZgBASAIQATAGAIANQAJAMAEATIgjAGQgCgQgLgKQgMgJgUAAQgYAAgLAIQgKAJAAAKQAAAHAEAFQAEAEAKADIAfAJQAlAKAPAHQAPAGAIAMQAIAMAAATQAAARgKAQQgKAPgUAJQgTAIgYAAQgpAAgVgRgAjAB2QgbgdAAgzQAAgyAbgdQAbgcArAAQAqAAAaAbQAbAdAAAyIgBAJIiaAAQACAiARASQARATAaAAQAUAAANgLQAOgKAIgXIAkAFQgIAggXARQgYASgkAAQgtAAgbgbgAiigYQgRAPgBAaIB0AAQgDgZgLgNQgRgTgagBQgZABgQAQgAmMBzIAAAZIghAAIAAkcIAjAAIAABmQAWgbAjAAQATAAARAHQARAIALAOQALAOAHAUQAGARAAAXQAAA1gbAdQgaAdglAAQglAAgUgegAl8gVQgRAUAAAkQAAAmAKAQQARAbAcABQAXgBARgTQARgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgAu0CKQgQgHgIgLQgHgKgEgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcADAJQADAOALAIQAKAIAQAAQAQAAAOgIQAOgIAGgOQAFgOAAgbIAAhtIAkAAIAADNIggAAIAAgeQgYAjgqAAQgSAAgQgHgATTCMIAAh+QAAgTgFgKQgEgMgKgGQgLgGgOAAQgWAAgQAOQgRAOAAAmIAABxIgjAAIAAjNIAgAAIAAAeQAXgjArABQATAAAPAGQAQAHAIALQAIALADAPQACAKAAAWIAAB/gALhCMIhPjNIAlAAIAsB6QAIAVAGAVQAEgRAJgXIAuh8IAkAAIhODNgAANCMIAAjNIAfAAIAAAgQAMgXALgGQAKgIAMABQASgBASALIgMAiQgNgJgMABQgMAAgJAHQgJAHgEAMQgGARAAAWIAABsgAoECMIAAiCQAAgUgDgIQgEgKgJgFQgJgGgMAAQgWAAgOAPQgOAOAAAeIAAB4IgkAAIAAiHQAAgVgIgLQgJgMgTAAQgPAAgNAHQgMAJgGAPQgGANAAAcIAABrIgjAAIAAjNIAgAAIAAAdQAJgPARgJQAQgJAUAAQAYAAAOAJQAPAKAGARQAZglAnABQAfAAARARQAQAQAAAkIAACMgAw6CMIiWjfIAADfIglAAIAAkcIAnAAICWDfIAAjfIAlAAIAAEcg")
        shape_6.setTransform(221.7,24.1)
    
        const shape_7 = new window.createjs.Shape()
        shape_7.graphics.f("#FFFFFF").s().p("AKgCoQgXgQABgiIAiAFQACAQAKAHQANAKAXAAQAYAAANgKQANgKAFgRQADgLAAgiQgXAbgjAAQgqAAgYgfQgXgfAAgpQAAgeAKgZQALgZAVgOQAUgNAbAAQAlAAAYAdIAAgZIAgAAIAACyQAAAwgJAUQgKAUgWAMQgVAMgfAAQglAAgXgRgAK3g9QgQATAAAlQAAAnAQATQAQATAZAAQAYAAAQgTQARgTAAglQAAgngRgTQgRgTgYAAQgXAAgRATgAFoBOQgbgdAAgxQAAg0AbgcQAbgdArAAQAqAAAaAcQAbAcAAA0IgBAHIiaAAQACAiARASQARATAaAAQAUAAANgLQAOgKAIgWIAkAEQgIAggXASQgYARgkAAQgtAAgbgbgAGGhAQgRAQgBAbIB0AAQgDgagLgNQgRgUgaAAQgZAAgQAQgAhoBOQgbgdAAgxQAAg0AbgcQAbgdArAAQAoAAAaAcQAbAcAAA0IgBAHIiYAAQACAiARASQARATAaAAQAUAAAMgLQANgKAIgWIAkAEQgIAggXASQgYARgiAAQgtAAgbgbgAhKhAQgRAQgBAbIByAAQgDgagLgNQgPgUgaAAQgZAAgQAQgAk0BLIAAAaIghAAIAAkdIAjAAIAABnQAWgcAjAAQATAAARAHQARAIALAOQALAOAHAUQAGATAAAXQAAAzgbAdQgaAdglAAQglAAgUgegAkkg8QgRAUAAAlQAAAkAKAQQARAcAcAAQAXAAARgUQARgVAAglQAAgpgQgTQgQgTgXAAQgXAAgRAUgAtcBiQgQgHgIgKQgHgLgEgPQgCgLAAgWIAAh/IAjAAIAABxQAAAcADAJQADAOALAIQAKAIAQAAQAQAAAOgIQAOgIAGgOQAFgOAAgbIAAhtIAkAAIAADOIggAAIAAgfQgYAjgqAAQgSAAgQgHgARmBhQgLgGgEgJQgEgKAAggIAAh1IgaAAIAAgcIAaAAIAAgzIAjgVIAABIIAjAAIAAAcIgjAAIAAB3QAAAPABAEQACAFAFACQAEADAHAAIAQgCIAFAfQgPADgMAAQgTAAgKgGgAP0BlIAAiCQAAgagLgMQgMgMgVAAQgPAAgOAIQgOAIgGAOQgGAOAAAYIAABwIgjAAIAAkdIAjAAIAABnQAZgcAlAAQAXAAARAJQARAJAIAQQAHAQAAAeIAACCgAI3BlIAAjOIAjAAIAADOgABlBlIAAjOIAfAAIAAAgQAMgWALgHQAKgHAMAAQASAAASALIgMAhQgNgIgMAAQgMAAgJAHQgJAHgEAMQgGATAAAWIAABrgAmsBlIAAiBQAAgVgDgJQgEgKgJgFQgJgGgMAAQgWAAgOAPQgOAOAAAgIAAB3IgkAAIAAiFQAAgXgIgMQgJgMgTAAQgPAAgNAIQgMAIgGAPQgGAPAAAcIAABqIgjAAIAAjOIAgAAIAAAdQAJgPARgJQAQgJAUAAQAYAAAOAJQAPAKAGARQAZgkAnAAQAfAAARARQAQARAAAjIAACNgAviBlIiWjfIAADfIglAAIAAkdIAnAAICWDfIAAjfIAlAAIAAEdgAI3iPIAAgpIAjAAIAAApg")
        shape_7.setTransform(222.9,28.1)
    
        const shape_8 = new window.createjs.Shape()
        shape_8.graphics.f("#FFFFFF").s().p("AO7B2QgbgdAAgzQAAgyAbgdQAbgcArAAQAqAAAaAbQAbAdAAAyIgBAJIiaAAQACAiARASQARATAaAAQAUAAANgLQAOgKAIgXIAkAFQgIAggXARQgYASgkAAQgtAAgbgbgAPZgYQgRAPgBAaIB0AAQgDgZgLgNQgRgTgagBQgZABgQAQgAgqB2QgbgdAAgzQAAgyAbgdQAbgcApAAQAqAAAaAbQAbAdAAAyIgBAJIiYAAQACAiARASQAPATAaAAQAUAAANgLQAOgKAIgXIAkAFQgIAggXARQgYASgkAAQgrAAgbgbgAgMgYQgRAPgBAaIByAAQgDgZgLgNQgRgTgagBQgZABgOAQgAj2BzIAAAZIghAAIAAkcIAjAAIAABmQAWgbAjAAQATAAARAHQARAIALAOQALAOAHAUQAGARAAAXQAAA1gbAdQgaAdglAAQglAAgUgegAjmgVQgRAUAAAkQAAAmAKAQQARAbAcABQAXgBARgTQARgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgAseCKQgQgHgIgLQgHgKgEgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcADAJQADAOALAIQAKAIAQAAQAQAAAOgIQAOgIAGgOQAFgOAAgbIAAhtIAkAAIAADNIggAAIAAgeQgYAjgqAAQgSAAgQgHgANUCMIAAh+QAAgTgFgKQgEgMgKgGQgLgGgOAAQgWAAgQAOQgRAOAAAmIAABxIgjAAIAAjNIAgAAIAAAeQAXgjArABQATAAAPAGQAQAHAIALQAIALADAPQACAKAAAWIAAB/gAJ1CMIAAjNIAjAAIAADNgAIdCMIAAh+QAAgTgFgKQgEgMgKgGQgLgGgOAAQgWAAgQAOQgRAOAAAmIAABxIgjAAIAAjNIAgAAIAAAeQAXgjArABQATAAAPAGQAQAHAIALQAIALADAPQACAKAAAWIAAB/gACjCMIAAjNIAfAAIAAAgQAMgXALgGQAKgIAMABQASgBASALIgMAiQgNgJgMABQgMAAgJAHQgJAHgEAMQgGARAAAWIAABsgAluCMIAAiCQAAgUgDgIQgEgKgJgFQgJgGgMAAQgWAAgOAPQgOAOAAAeIAAB4IgkAAIAAiHQAAgVgIgLQgJgMgTAAQgPAAgNAHQgMAJgGAPQgGANAAAcIAABrIgjAAIAAjNIAgAAIAAAdQAJgPARgJQAQgJAUAAQAYAAAOAJQAPAKAGARQAZglAnABQAfAAARARQAQAQAAAkIAACMgAukCMIiWjfIAADfIglAAIAAkcIAnAAICWDfIAAjfIAlAAIAAEcgAJ1hoIAAgoIAjAAIAAAog")
        shape_8.setTransform(222.3,24.1)
    
        const shape_9 = new window.createjs.Shape()
        shape_9.graphics.f("#FFFFFF").s().p("AJ/B2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgAKdgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAA+B2QgbgdAAgzQAAgyAbgdQAbgcArAAQApAAAbAbQAaAdAAAyIAAAJIibAAQACAiASASQARATAaAAQATAAAOgLQAOgKAIgXIAkAFQgJAggXARQgXASgkAAQguAAgagbgABcgYQgRAPgCAaIB0AAQgCgZgLgNQgRgTgbgBQgYABgQAQgAiNBzIAAAZIghAAIAAkcIAkAAIAABmQAWgbAiAAQAUAAARAHQARAIALAOQALAOAGAUQAEARAAAXQAAA1gYAdQgaAdglAAQglAAgVgegAh9gVQgQAUAAAkQAAAmAKAQQAQAbAdABQAXgBARgTQAQgVAAgnQAAgngQgUQgQgSgXgBQgXABgRATgAq0CKQgQgHgIgLQgIgKgDgQQgCgKAAgWIAAh/IAjAAIAABxQAAAcACAJQADAOALAIQALAIAQAAQAQAAANgIQAOgIAGgOQAGgOAAgbIAAhtIAjAAIAADNIgfAAIAAgeQgZAjgpAAQgTAAgPgHgAIaCJQgKgGgFgKQgEgJAAggIAAh2IgaAAIAAgbIAaAAIAAgzIAjgWIAABJIAjAAIAAAbIgjAAIAAB4QAAAPACAEQACAEAEADQAEADAIgBIAPgBIAFAfQgOADgMAAQgTAAgLgGgAPTCMIAAh+QAAgTgEgKQgEgMgLgGQgKgGgOAAQgXAAgQAOQgQAOAAAmIAABxIgjAAIAAjNIAfAAIAAAeQAXgjArABQATAAAQAGQAPAHAIALQAIALADAPQACAKAAAWIAAB/gAEMCMIAAjNIAgAAIAAAgQAMgXAKgGQAKgIANABQASgBASALIgMAiQgNgJgNABQgLAAgKAHQgJAHgEAMQgGARAAAWIAABsgAkECMIAAiCQAAgUgEgIQgDgKgJgFQgJgGgMAAQgWAAgPAPQgOAOAAAeIAAB4IgjAAIAAiHQAAgVgJgLQgIgMgUAAQgPAAgMAHQgNAJgGAPQgFANAAAcIAABrIgjAAIAAjNIAfAAIAAAdQAKgPAQgJQAQgJAVAAQAXAAAPAJQAOAKAHARQAYglAoABQAeAAARARQARAQAAAkIAACMgAs7CMIiWjfIAADfIgkAAIAAkcIAnAAICWDfIAAjfIAkAAIAAEcg")
        shape_9.setTransform(221.7,24.1)
    
        this.text.timeline.addTween(window.createjs.Tween.get({}).to({state:[{t:shape_0}]}).to({state:[{t:shape_1}]},1).to({state:[{t:shape_2}]},1).to({state:[{t:shape_3}]},1).to({state:[{t:shape_4}]},1).to({state:[{t:shape_5}]},1).to({state:[{t:shape_6}]},1).to({state:[{t:shape_7}]},1).to({state:[{t:shape_8}]},1).to({state:[{t:shape_9}]},1).to({state:[{t:shape_0}]},1).to({state:[{t:shape_1}]},1).to({state:[{t:shape_2}]},1).to({state:[{t:shape_3}]},1).to({state:[{t:shape_4}]},1).to({state:[{t:shape_5}]},1).to({state:[{t:shape_6}]},1).to({state:[{t:shape_7}]},1).to({state:[{t:shape_8}]},1).to({state:[{t:shape_9}]},1).to({state:[{t:shape_0}]},1).to({state:[{t:shape_1}]},1).to({state:[{t:shape_2}]},1).to({state:[{t:shape_3}]},1).to({state:[{t:shape_4}]},1).to({state:[{t:shape_5}]},1).to({state:[{t:shape_6}]},1).to({state:[{t:shape_7}]},1).to({state:[{t:shape_8}]},1).to({state:[{t:shape_9}]},1).to({state:[{t:shape_0}]},1).to({state:[{t:shape_1}]},1).to({state:[{t:shape_2}]},1).to({state:[{t:shape_3}]},1).to({state:[{t:shape_4}]},1).wait(1))
        // this.text.gotoAndPlay("start")
    }
    setChangeImg(config) {
        if(Object.prototype.toString.call(config) !== '[object Object]') {
            return
        }

        // if(stage.__proto__ !== window.createjs.Stage.prototype) {
        //     return
        // }
        this.changeImg = new window.createjs.MovieClip(config)
        this.changeImg.nominalBounds = new window.createjs.Rectangle(0,0,534.9,430.3)
        // stage.addChild(this.changeImg)
        let tween = window.createjs.Tween.get({})
        Object.keys(this.images).forEach((item, index) => {
            this.images[item].setTransform(0,0,0.798,0.798)
            tween = index ? tween.to({
                state: [{ t:  this.images[item].setTransform(200,200,0.798,0.798) }]
            }, 1) : tween.to({
                state: [{ t:  this.images[item].setTransform(0,0,0.798,0.798) }]
            })
        })
        
        this.changeImg.timeline.addTween(tween.wait(1))
        // this.changeImg.gotoAndPlay("start")
    }
    setUnit36(stage) {
        if(stage.__proto__ !== window.createjs.Stage.prototype) {
            return
        }
        this.unit36 = new window.createjs.Container()
        this.unit36.nominalBounds = new window.createjs.Rectangle(-33.5,-26.5,67,53)
        stage.addChild(this.unit36)
        console.log('this.images[right]: ', this.images['right']);

        this.unit36.addChild(this.images['right'].setTransform(-33.5,-26.5))
        stage.addChild(this.unit36)
    }
}